name: red-flagger
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - joblib
  - matplotlib
  - seaborn
  - requests
  - jupyterlab
  - notebook
  - ipywidgets
  - pytorch
  - torchvision
  - pip:
      - ultralytics
      - transformers
      - accelerate
      - safetensors
      - tensorflow
      - tensorflowjs
      - onnx
      - onnxruntime
